dist: xenial
language: bash
services:
    - docker
before_script:
    - docker-compose up -d sqlserver    
    - sleep 5
    - chmod +x ./sqlserver/wait.sh
    - chmod +x ./sqlserver/create-database.sh
    - chmod +x ./sqlserver/support/run.sh
    - docker-compose exec sqlserver ./wait.sh
    - docker-compose exec sqlserver ./create-database.sh
    - sleep 3
script:
    - docker-compose exec sqlserver ./support/run.sh ./demo