version: '3.4'

services:

  sqlserver:
    build: sqlserver
    image: learning:sqlserver
    container_name: learning-sqlserver
    ports:
      - "1477:1433"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - .:/usr/local/src  

  oracle:
    build: oracle
    image: learning:oracle
    container_name: learning-oracle
    ports:
      - "1521:1521"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - .:/usr/local/src  
