version: '3.4'

services:

  sqlserver:
    build: sqlserver
    image: sqlserver:ready
    container_name: sqlserver
    ports:
      - "1455:1433"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - sqlserver/scripts:/usr/local/src

  
