version: '3.4'

services:

  sqlserver:
    build: sqlserver
    image: sqlserver:studyexecutionplan
    container_name: sqlserver-studyexecutionplan
    ports:
      - "1477:1433"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - ./sqlserver:/usr/local/src

  
