version: '3.4'

services:

  sqlserver:
    build: sqlserver
    image: learning:sqlserver
    container_name: learning-sqlserver
    ports:
      - "1477:1433"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - .:/usr/local/src  

  oracle:
    build: oracle
    image: learning:oracle
    container_name: learning-oracle
    ports:
      - "1521:1521"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - .:/usr/local/src  

  postgresql:
    build: postgresql
    image: learning:postgresql
    container_name: learning-postgresql
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=exploration
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    volumes:
      - .:/usr/local/src  

