USE exploration
GO
SET NOCOUNT ON
GO
	
DROP TABLE IF EXISTS PAYMENT_ORDER
DROP TABLE IF EXISTS PAYMENT_HISTORY
CREATE TABLE PAYMENT_ORDER (
    ID int,
    AMOUNT int,
    PAID bit
)
CREATE TABLE PAYMENT_HISTORY (
    SESSION int,
    PAYMENT_ORDER_ID int,
    STATUS varchar(10)
)
GO
insert into PAYMENT_ORDER (ID, AMOUNT, PAID) values (1, 15, 0)
insert into PAYMENT_ORDER (ID, AMOUNT, PAID) values (2, 30, 1)
insert into PAYMENT_ORDER (ID, AMOUNT, PAID) values (3, 45, 0)
insert into PAYMENT_HISTORY(SESSION, PAYMENT_ORDER_ID, STATUS) values (1, 2, "SUCCESS")
GO

insert into PAYMENT_HISTORY (SESSION, PAYMENT_ORDER_ID, STATUS)
    select  2, ID, "READY" 
    from    PAYMENT_ORDER
    where   PAID = 0

select * from PAYMENT_HISTORY