name: SqlServer tests

on:
  push:
    branches:
      - master

jobs:
  info:
    name: about docker
    runs-on: ubuntu-latest
    steps:
      - name: versions
        run: |
          docker version
          docker compose version

  tests:
    needs: info
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout submodule
        run: git submodule update --init
      - name: Build
        run: docker compose build sqlserver
      - name: Start
        run: docker compose up -d sqlserver
      - name: Run tests
        run: |
          docker exec learning-sqlserver ./support/yop-testing-bash/dist/test.sh ./sqlserver
